name: gnome-browser-connector
version: 42.1-r1
source:
  url: https://download.gnome.org/sources/gnome-browser-connector/42/gnome-browser-connector-42.1.tar.xz
build:
- meson setup build --prefix=$PREFIX
- meson compile -C build
- DESTDIR=$DESTDIR meson install -C build
depends:
  build:
  - pygobject
  runtime:
  - gnome-shell
