name: pydantic
version: 2.13.4
source:
  url: https://github.com/pydantic/pydantic/archive/refs/tags/v2.13.4.tar.gz
build:
- pip install . --root=$DESTDIR --prefix=$PREFIX
depends:
  build:
  - hatch-fancy-pypi-readme
  - maturin
  - cloudpickle
  - dirty-equals
  - email-validator
  - faker
  - jsonschema
  - pytz
  - rich
  - annotated-types
  - typing-extensions
  - typing-inspection
  - tzdata
  - pydantic-core
  runtime:
  - annotated-types
  - typing-extensions
  - typing-inspection
  - tzdata
  - pydantic-core
