name: xdg
version: 3.21.1
source:
  url: https://github.com/ocaml/dune/archive/3.21.1.tar.gz
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
depends:
  build:
  - dune-3
