name: aunit
version: 26.0.0
source:
  url: https://github.com/AdaCore/aunit/archive/refs/tags/v26.0.0.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - sphinx
  - sphinx-rtd-theme
