name: nettle
version: 3.10.2
source:
  url: https://ftp.gnu.org/gnu/nettle/nettle-3.10.2.tar.gz
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
depends:
  build:
  - m4
  - texinfo
  - openpgp-keys-nettle
  - gmp
