name: kdiagram
version: 3.0.1
source:
  url: https://download.kde.org/stable/stable/kdiagram/3.0.1/kdiagram-3.0.1.tar.xz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - qttools-
  - qtbase-
  - qtsvg-
