name: a2ps
version: 4.15.6
source:
  url: https://ftp.gnu.org/gnu/a2ps/a2ps-4.15.6.tar.gz
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
depends:
  build:
  - yacc
  - gperf-2
  - gettext
  - ghostscript-gpl
  - libpaper
  - psutils-1
  - wdiff
  - bash
  - boehm-gc
  - coreutils-6
  - emacs-23
  - latex-base
  - libintl
  runtime:
  - ghostscript-gpl
  - libpaper
  - psutils-1
  - wdiff
  - bash
  - boehm-gc
  - coreutils-6
  - emacs-23
  - latex-base
  - libintl
