name: biblio
version: '0.3'
source:
  url: https://github.com/cpitclaudel/biblio.el/archive/0.3.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - buttercup
  - noflet
  - undercover
  - dash
  runtime:
  - dash
