name: endless-sky
version: 0.11.2
source:
  url: https://github.com/endless-sky/endless-sky/archive/refs/tags/v0.11.2.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - pkgconfig
  - flac
  - libavif
  - libglvnd
  - libjpeg-turbo
  - libmad
  - libpng
  - libsdl2
  - openal
  - util-linux
  - minizip
  - glew
  runtime:
  - flac
  - libavif
  - libglvnd
  - libjpeg-turbo
  - libmad
  - libpng
  - libsdl2
  - openal
  - util-linux
  - minizip
  - glew
