name: with-editor
version: 3.5.3
source:
  url: https://github.com/magit/with-editor/archive/v3.5.3.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - texinfo
  - compat
  - cond-let
  - llama
  runtime:
  - compat
  - cond-let
  - llama
