name: screen
version: 5.0.1
source:
  url: https://ftp.gnu.org/gnu/screen/screen-5.0.1.tar.gz
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
depends:
  build:
  - texinfo
  - ncurses
  - libcrypt
  - pam
  runtime:
  - utmp
  - selinux-screen
  - libutempter
