name: sdl-jstest
version: 0.2.2
source:
  url: https://github.com/Grumbel/sdl-jstest/archive/v0.2.2/sdl-jstest-0.2.2.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - appstream-glib
  - tinycmmc
  - pkgconfig
  - libsdl
  - libsdl2
  - ncurses
