name: django-timezone-field
version: 7.2.2
source:
  url: https://github.com/mfogel/django-timezone-field/archive/7.2.2.tar.gz
build:
- pip install . --root=$DESTDIR --prefix=$PREFIX
depends:
  build:
  - djangorestframework
  - pytz
  - django-2
  runtime:
  - django-2
