name: minissdpd
version: 1.6.0
source:
  url: https://miniupnp.tuxfamily.org/files/minissdpd-1.6.0.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - openpgp-keys-miniupnp
  - libnfnetlink
  runtime:
  - miniupnpd
  - miniupnpc
  - selinux-minissdpd
