name: ppx_ignore_instrumentation
version: 0.16.0
source:
  url: https://github.com/janestreet/ppx_ignore_instrumentation/archive/refs/tags/v0.16.0.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - ppxlib
