name: levenshtein
version: 0.27.5
source:
  url: https://github.com/rapidfuzz/Levenshtein/archive/v0.27.5.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - cython
  - scikit-build-core
  - rapidfuzz-cpp
  runtime:
  - rapidfuzz
