name: compat
version: 31.0.0.1
source:
  url: https://github.com/emacs-compat/compat/archive/31.0.0.1.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - texinfo
