name: unison
version: 2.53.8
source:
  url: https://github.com/bcpierce00/unison/archive/refs/tags/v2.53.8.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - ocaml
  - dvipsk
  - ghostscript-gpl
  - texlive-latex
  runtime:
  - ocaml
  - lablgtk
  - ssh-askpass-fullscreen
  - x11-ssh-askpass
