name: diffoscope
version: '323'
source:
  url: https://diffoscope.org/archive/diffoscope-323.tar.bz2
build:
- pip install . --root=$DESTDIR --prefix=$PREFIX
depends:
  build:
  - 7zip
  - p7zip
  - docx2txt
  - html2text
  - libcaca
  - imagemagick-tools
  - openpgp-keys-chrislamb
  - python-magic
  - file
  - libarchive-c
  - distro
  - python-tlsh
  - h5py
  - pypdf
  - acl
  - binutils
  - bzip2
  - colord
  - cpio
  - diffutils
  - dtc
  - e2fsprogs
  - findutils
  - gettext
  - giflib
  - gnupg
  - ghc
  - hdf5
  - vim-core
  - imagemagick
  - cdrtools
  - jdk
  - libguestfs
  - llvm
  - xz-utils
  - mono
  - odt2txt
  - fpc
  - pdftk
  - poppler
  - ghostscript-gpl
  - R
  - rpm
  - sqlite
  - squashfs-tools
  - openssh
  - tar
  - tcpdump
  - unzip
  - gzip
  - zstd
  runtime:
  - python-magic
  - file
  - libarchive-c
  - distro
  - python-tlsh
  - h5py
  - pypdf
  - acl
  - binutils
  - bzip2
  - libcaca
  - colord
  - cpio
  - diffutils
  - docx2txt
  - dtc
  - e2fsprogs
  - findutils
  - gettext
  - giflib
  - gnupg
  - ghc
  - hdf5
  - vim-core
  - imagemagick
  - cdrtools
  - jdk
  - libguestfs
  - llvm
  - xz-utils
  - mono
  - odt2txt
  - fpc
  - pdftk
  - poppler
  - ghostscript-gpl
  - R
  - rpm
  - sqlite
  - squashfs-tools
  - openssh
  - tar
  - tcpdump
  - unzip
  - gzip
  - zstd
