name: nix-mode
version: 1.5.0
source:
  url: https://github.com/NixOS/nix-mode/archive/v1.5.0.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - company-mode
  - magit
  - mmm-mode
  - transient
  runtime:
  - company-mode
  - magit
  - mmm-mode
  - transient
