name: grpc
version: 1.80.0
source:
  url: https://github.com/grpc/grpc/archive/refs/tags/v1.80.0.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
