name: opensmt
version: 2.9.2
source:
  url: https://github.com/usi-verification-and-security/opensmt/archive/v2.9.2.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - yacc
  - lex
  - gtest
  - gmp
  - libedit
  runtime:
  - gmp
  - libedit
