name: libavif
version: 1.4.1
source:
  url: https://github.com/AOMediaCodec/libavif/archive/v1.4.1.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - pkgconfig
  - libjpeg-turbo
  - libpng
  - libaom
  - dav1d
  - gtest
  - imagemagick
  - glib
  - gdk-pixbuf
  - rav1e
  - svt-av1
  - libyuv
