name: ngspice
version: '46'
source:
  url: https://downloads.sourceforge.net/ngspice/ngspice-46.tar.gz
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
depends:
  build:
  - ncurses
  - libXaw
  - libXt
  - libX11
  - fftw
  - readline
  - tcl
  - blt
