name: meanwhile
version: 1.1.1
source:
  url: https://github.com/obriencj/meanwhile/archive/refs/tags/v1.1.1.tar.gz
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
depends:
  build:
  - pkgconfig
  - doxygen
  - glib
  runtime:
  - glib
