name: lightspark
version: 0.9.0
source:
  url: https://github.com/lightspark/lightspark/archive/0.9.0.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - nasm
  - pkgconfig
  - xz-utils
  - glib
  - libpcre
  - liberation-fonts
  - freetype
  - libjpeg-turbo
  - libpng
  - libsdl2
  - zlib
  - cairo
  - libX11
  - pango
  - curl
  - ffmpeg
  - libglvnd
  - glew
  - opengl
  - rtmpdump
  runtime:
  - xz-utils
  - glib
  - libpcre
  - liberation-fonts
  - freetype
  - libjpeg-turbo
  - libpng
  - libsdl2
  - zlib
  - cairo
  - libX11
  - pango
  - curl
  - ffmpeg
  - libglvnd
  - glew
  - opengl
  - rtmpdump
