name: rg
version: 2.4.1
source:
  url: https://github.com/dajva/rg.el/archive/2.4.1.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - s
  - undercover
  - transient
  - wgrep
  runtime:
  - ripgrep
