name: xmlsec
version: 1.3.17
source:
  url: https://github.com/xmlsec/python-xmlsec/archive/1.3.17.tar.gz
build:
- pip install . --root=$DESTDIR --prefix=$PREFIX
depends:
  build:
  - lxml
  - pkgconfig
  - setuptools-scm
  - wheel
  - libxml2
  - xmlsec
  runtime:
  - lxml
