name: no-littering
version: 1.9.0
source:
  url: https://github.com/emacscollective/no-littering/archive/v1.9.0.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - compat
  runtime:
  - compat
