name: gsasl
version: 2.2.2
source:
  url: https://ftp.gnu.org/gnu/gsasl/gsasl-2.2.2.tar.gz
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
depends:
  build:
  - libgsasl
  - readline
  - libgcrypt
  - gnutls
  - libidn
  - libgssglue
  - gettext
  - libntlm
