name: ocserv
version: 1.4.1
source:
  url: https://www.infradead.org/ocserv/download/ocserv-1.4.1.tar.xz
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
depends:
  build:
  - openpgp-keys-ocserv
