name: core_unix
version: 0.17.1
source:
  url: https://github.com/janestreet/core_unix/archive/refs/tags/v0.17.1.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - dune
  - ocaml
  - core
  - core_kernel
  - expect_test_helpers_core
  - jane-street-headers
  - jst-config
  - ppx_jane
  - ppx_optcomp
  - sexplib
  - spawn
  - timezone
  - uopt
  runtime:
  - ocaml
  - core
  - core_kernel
  - expect_test_helpers_core
  - jane-street-headers
  - jst-config
  - ppx_jane
  - ppx_optcomp
  - sexplib
  - spawn
  - timezone
  - uopt
