name: grpcio-status
version: 1.82.0
source:
  url: https://github.com/grpc/grpc/archive/v1.82.0.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - coverage
  - grpcio-
  - googleapis-common-protos
  - protobuf
  runtime:
  - grpcio-
  - googleapis-common-protos
  - protobuf
