name: s6-networking-man-pages
version: 2.7.0.4.1
source:
  url: https://git.sr.ht/~flexibeast/s6-networking-man-pages/archive/v2.7.0.4.1.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
