name: gpr
version: 26.0.0
source:
  url: https://github.com/AdaCore/gpr/archive/refs/tags/v26.0.0.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - e3-testsuite
  - gnatmem
  - xmlada
  - gnatcoll-core
  - gnatcoll-bindings
  runtime:
  - xmlada
  - gnatcoll-core
  - gnatcoll-bindings
