name: brotlicffi
version: 1.2.0.1
source:
  url: https://github.com/python-hyper/brotlicffi/archive/v1.2.0.1.tar.gz
build:
- pip install . --root=$DESTDIR --prefix=$PREFIX
depends:
  build:
  - cffi
  - brotli
