name: line-profiler
version: 5.0.2
source:
  url: https://github.com/pyutils/line_profiler/archive/v5.0.2.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - cython
  - coverage
  - ubelt
  - ipython
  runtime:
  - ipython
