name: gcompris
version: 25.1.1
source:
  url: https://gcompris.net/download/qt/src/gcompris-qt-25.1.1.tar.xz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
depends:
  build:
  - qttools-
  - cppcheck
  - clang
  - qtbase-
  - qtcharts-
  - qtdeclarative-
  - qtmultimedia-
  - qtsensors-
  - qtsvg-
  runtime:
  - qtimageformats-
  - qtmultimedia-
  - qtsensors-
