name: ueberzug
version: 18.3.1
source:
  url: https://github.com/ueber-devel/ueberzug/archive/refs/tags/18.3.1.tar.gz
build:
- meson setup build --prefix=$PREFIX
- meson compile -C build
- DESTDIR=$DESTDIR meson install -C build
depends:
  build:
  - libX11
  - libXext
  - libXres
  runtime:
  - attrs
  - docopt
  - pillow
  - ueberzugpp
