name: tree-sitter-powershell
version: 0.26.5
source:
  url: https://github.com/airbus-cert/tree-sitter-powershell/archive/v0.26.5.tar.gz
build:
- cmake -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
- cmake --build build -j$(nproc)
- DESTDIR=$DESTDIR cmake --install build
