name: owslib
version: 0.36.0
source:
  url: https://github.com/geopython/owslib/archive/0.36.0.tar.gz
build:
- pip install . --root=$DESTDIR --prefix=$PREFIX
depends:
  build:
  - pillow
  - lxml
  - python-dateutil
  - pyyaml
  - requests
  runtime:
  - lxml
  - python-dateutil
  - pyyaml
  - requests
