name: dune-format
version: '0.1'
source:
  url: https://github.com/purcell/emacs-dune-format/archive/0.1.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - reformatter
  runtime:
  - dune
