name: open-test-reporting-events-0.2.0_pre1
version: '0'
source:
  url: https://gitlab.freedesktop.org/open-test-reporting-events-0.2.0_pre1/open-test-reporting-events-0.2.0_pre1/-/archive/0/open-test-reporting-0.1.0-M1.tar.gz
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
