name: scx-loader
version: 1.1.2
source:
  url: https://github.com/sched-ext/scx-loader/archive/refs/tags/v1.1.2.tar.gz
build:
- cargo build --release
- mkdir -p $DESTDIR$PREFIX/bin
- cp target/release/scx-loader $DESTDIR$PREFIX/bin/
depends:
  build:
  - scx-
  runtime:
  - scx-
