name: rygel
version: '45.2'
source:
  url: https://download.gnome.org/sources/rygel/45/rygel-45.2.tar.xz
build:
- meson setup build --prefix=$PREFIX
- meson compile -C build
- DESTDIR=$DESTDIR meson install -C build
depends:
  build:
  - docbook-xml-dtd
  - gettext
  - pkgconfig
  - gupnp
  - libgee
  - gssdp
  - glib
  - libxml2
  - gupnp-av
  - gupnp-dlna
  - libsoup
  - sqlite
  - libunistring
  - gstreamer
  - gst-plugins-base
  - gstreamer-editing-services
  - libmediaart
  - gst-plugins-soup
  - gdk-pixbuf
  - util-linux
  - shared-mime-info
  - gobject-introspection
  - tinysparql
  - gst-plugins-bad
  - gst-plugins-twolame
  - gst-plugins-libav
  - gtk
  - libX11
