name: fwupd
version: 2.0.20
source:
  url: https://github.com/fwupd/fwupd/releases/download/2.0.20/fwupd-2.0.20.tar.xz
build:
- meson setup build --prefix=$PREFIX
- meson compile -C build
- DESTDIR=$DESTDIR meson install -C build
depends:
  build:
  - jinja2
  - meson
  - pkgconfig
  - hwdata
  - markdown
  - gi-docgen
  - bash-completion
  - gobject-introspection
  - gnutls
  - pygobject
  - openpgp-keys-hughsie
  runtime:
  - dbus
  - selinux-fwupd
