name: libshumate
version: 1.6.1
source:
  url: https://download.gnome.org/sources/libshumate/1.6/libshumate-1.6.1.tar.xz
build:
- meson setup build --prefix=$PREFIX
- meson compile -C build
- DESTDIR=$DESTDIR meson install -C build
depends:
  build:
  - glib-utils
  - gperf
  - gi-docgen
  - glib
  - cairo
  - sqlite
  - gtk
  - libsoup
  - gobject-introspection
  - json-glib
  - protobuf-c
  runtime:
  - glib
  - cairo
  - sqlite
  - gtk
  - libsoup
  - gobject-introspection
  - json-glib
  - protobuf-c
