name: getuto
version: '2.0'
source:
  url: https://github.com/projg2/getuto/archive/refs/tags/getuto-2.0.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - gpg
  - openssl
  - openpgp-keys-gentoo-release
  - gentoo-functions
  runtime:
  - gpg
  - openssl
  - openpgp-keys-gentoo-release
  - gentoo-functions
