name: gom
version: 0.5.6
source:
  url: https://download.gnome.org/sources/gom/0.5/gom-0.5.5.tar.xz
build:
- meson setup build --prefix=$PREFIX
- meson compile -C build
- DESTDIR=$DESTDIR meson install -C build
depends:
  runtime:
  - sqlite
  - glib
  - gobject-introspection
  - pygobject
