name: markdown-mode
version: '2.8'
source:
  url: https://github.com/jrblevin/markdown-mode/archive/v2.8.tar.gz
build:
- make -j$(nproc)
- make DESTDIR=$DESTDIR PREFIX=$PREFIX install
depends:
  build:
  - pandoc
  - aspell
  - hunspell
  - markdown2
  - markdown
  runtime:
  - markdown2
  - markdown
  - pandoc
