name: rnnoise
version: 0.4.1_p20210122-r1
source:
  url: https://gitlab.xiph.org/xiph/rnnoise/-/archive/1cbdbcf1283499bbb2230a6b0f126eb9b236defd/rnnoise-1cbdbcf1283499bbb2230a6b0f126eb9b236defd.tar.bz2
build:
- ./configure --prefix=$PREFIX
- make -j$(nproc)
- make DESTDIR=$DESTDIR install
depends:
  build:
  - doxygen
  - graphviz
